### ISSUE TITLE
Lizenz hinzufügen

### ISSUE THREAD

**Issue by RealZone22** [noel-lang/awesome-fachinformatiker#1]
Hallo,

mir ist aufgefallen, dass dieses Repository derzeit keine Lizenz enthält. Ohne eine Lizenzdatei ist unklar, unter welchen Bedingungen der Inhalt genutzt und weiterverbreitet werden darf. Daher wäre es ratsam, eine Lizenz wie beispielsweise die MIT-Lizenz hinzuzufügen.

**Comment by cloudmaker97** [comment]
@noel-lang Besonders wichtig auch für Contributoren, denn schließlich darf der Inhalt ohne eine entsprechende Lizenz nicht bearbeitet werden und kann nicht auf Community-Arbeit basieren. Eine Zusammenfassung der rechtlichen Bedeutung: https://opensource.guide/de/legal/

**Comment by noel-lang** [comment]
Danke euch für den Hinweis! Habe das Repository um eine MIT-Lizenz ergänzt, ist denke recht sinnvoll für das Projekt. :)
